main: xyz.benw.plugins.fouriermc.FourierMC
name: FourierMC
version: 0.0.2
author: Ben
website:
description: Simple plugin to detect players using autoclickers.
commands:
   fmc:
      description: Base command
      usage: /<command> [arg]
permissions:
    fouriermc.*:
        description: Give access to all fouriermc commands
        children:
            fouriermc.fmc:
                description: Base command
                default: op